### ISSUE TITLE
How to get single card information?

### ISSUE THREAD

**Issue by jaqen404** [mpigsley/keyforge-arena#13]
if i know id of a single card,
how to get information of that card.
Do you know the api about single card?  
thanks.

**Comment by lako90** [comment]
nice question.. i used this source (https://github.com/keyforg/keyforge-cards-json/blob/master/cards.json) to make my own db card

**Comment by olpner** [comment]
How do I get the API key. I imagine that that is needed to be able to request info from the database. Am I on the right track?

**Comment by mpigsley** [comment]
I started this project before the official website was released. I [scraped the card information from aembertree](https://github.com/mpigsley/keyforge-arena/blob/master/bin/scrape-aembertree.js). The json list @lako90 referenced looks a bit more in depth than [my own](https://github.com/mpigsley/keyforge-arena/blob/master/src/constants/expansions/cota.json).

As far as the official API goes, you don't need an API key since it's all open. [Here's the function I use to fetch a particular deck and store it's information](https://github.com/mpigsley/keyforge-arena/blob/master/functions/src/submit-deck.js). I don't go and fetch individual card data every time.

**Comment by olpner** [comment]
@mpigsley Thanks, I'll take a look at your code. They don't have any official documentation of the API right? Does that mean that you've had to guess and use trial and error to scrape the site? I'm really new to this stuff...

**Comment by mpigsley** [comment]
For aembertree I didn't use their API. I just looped through each page and pulled the data directly from the HTML. Both sites (aembertree and official) do not have an official API. You can spy on the network requests in dev tools and reverse engineer the API based on what pages you are visiting though.
