### ISSUE TITLE
Application crashes after authentication using latest master

### ISSUE THREAD

**Issue by hickscorp** [mpigsley/keyforge-arena#2]
Running commit a9242c21b3c9e2a28753e1dc9ef835d4c5720e70, the application crashes upon logging in:

![image](https://user-images.githubusercontent.com/822933/49330678-d3f25980-f589-11e8-95ed-87e894c3ffe7.png)

I would suggest having either feature branches or functional tags allowing people to know what to checkout locally when testing.

**Comment by mpigsley** [comment]
@hickscorp at this point I'm just committing directly to master because I'm just trying to get it working. But yes. When it reaches a point at which people can successfully use the app, then semantic versioning and feature branches will become a thing!

If you'd like to help out on some development, my discord is `warpig#9483`. Let's chat.

**Comment by mpigsley** [comment]
Deployed a fix for this.
